const std = @import("std");
const cfg = @import("config"); // generated by build.zig: wg_size

const InArray = @SpirvType(.{ .runtime_array = f32 });
const OutArray = @SpirvType(.{ .runtime_array = f32 });
const InBuf = extern struct { data: InArray };
const OutBuf = extern struct { data: OutArray };

const input = @extern(*addrspace(.storage_buffer) const InBuf, .{
    .name = "input", .decoration = .{ .descriptor = .{ .set = 0, .binding = 0 } },
});
const output = @extern(*addrspace(.storage_buffer) OutBuf, .{
    .name = "output", .decoration = .{ .descriptor = .{ .set = 0, .binding = 1 } },
});

// Push constants: small block of data the host supplies per-dispatch, no descriptor
// set or buffer needed. Carries the runtime cutoff and element count.
const PushConstants = extern struct { threshold: f32, n: u32 };
const pc = @extern(*addrspace(.push_constant) const PushConstants, .{ .name = "pc" });

// Keep values strictly greater than the runtime threshold, zero the rest.
// Workgroup size (X) is baked in at compile time from `-Dwgsize`.
export fn main() callconv(.{ .spirv_kernel = .{ .x = cfg.wg_size, .y = 1, .z = 1 } }) void {
    const i = std.spirv.global_invocation_id[0];
    // The host dispatches ceil(n / wg_size) groups, so the last group may run
    // past the buffer — guard against it.
    if (i >= pc.n) return;
    const v = input.data[i];
    output.data[i] = if (v > pc.threshold) v else 0.0;
}
