const std = @import("std");
const c = @import("vk");
const cfg = @import("config"); // generated by build.zig: wg_size

/// Check for a Vulkan error
fn check(r: c.VkResult, what: []const u8) void {
    if (r != c.VK_SUCCESS) std.debug.panic("{s} failed: {d}\n", .{ what, r });
}

fn validationLayerAvailable(gpa: std.mem.Allocator) bool {
    var count: u32 = 0;
    _ = c.vkEnumerateInstanceLayerProperties(&count, null);
    const props = gpa.alloc(c.VkLayerProperties, count) catch return false;
    defer gpa.free(props);
    _ = c.vkEnumerateInstanceLayerProperties(&count, props.ptr);
    for (props) |p| {
        if (std.mem.eql(u8, std.mem.sliceTo(&p.layerName, 0), validation_layer)) return true;
    }
    return false;
}

// Must match the kernel's push-constant block: PushConstants{ threshold: f32, n: u32 }.
const PushConstants = extern struct { threshold: f32, n: u32 };

const validation_layer = "VK_LAYER_KHRONOS_validation";

pub fn main(init: std.process.Init) !void {
    // 0. Parse runtime flags: --threshold=<f>, --n=<u>, --validate.
    //    threshold and n travel to the GPU as push constants — no rebuild needed.
    var threshold: f32 = 128.0;
    var n: u32 = 256;
    var want_validation = false;
    {
        var it = init.minimal.args.iterate();
        _ = it.skip(); // argv[0]
        while (it.next()) |arg| {
            if (std.mem.startsWith(u8, arg, "--threshold=")) {
                threshold = std.fmt.parseFloat(f32, arg["--threshold=".len..]) catch threshold;
            } else if (std.mem.startsWith(u8, arg, "--n=")) {
                n = std.fmt.parseInt(u32, arg["--n=".len..], 10) catch n;
            } else if (std.mem.eql(u8, arg, "--validate")) {
                want_validation = true;
            }
        }
    }
    if (n == 0) n = 1;
    std.debug.print("config: n={d} wg_size={d} groups={d} threshold={d} validate={}\n", .{
        n, cfg.wg_size, (n + cfg.wg_size - 1) / cfg.wg_size, threshold, want_validation,
    });

    // 1. Instance (optionally with the validation layer, if installed)
    var app = std.mem.zeroes(c.VkApplicationInfo);
    app.sType = c.VK_STRUCTURE_TYPE_APPLICATION_INFO;
    app.apiVersion = c.VK_API_VERSION_1_2;
    var ici = std.mem.zeroes(c.VkInstanceCreateInfo);
    ici.sType = c.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ici.pApplicationInfo = &app;

    const layers = [_][*:0]const u8{validation_layer};
    if (want_validation) {
        if (validationLayerAvailable(init.gpa)) {
            ici.enabledLayerCount = 1;
            ici.ppEnabledLayerNames = &layers;
            std.debug.print("validation: enabled ({s})\n", .{validation_layer});
        } else {
            std.debug.print("validation: requested but '{s}' is not installed — continuing without it\n", .{validation_layer});
        }
    }

    var instance: c.VkInstance = undefined;
    check(c.vkCreateInstance(&ici, null, &instance), "vkCreateInstance");

    // 2. Physical device (first one)
    var pd_count: u32 = 1;
    var phys: c.VkPhysicalDevice = undefined;
    _ = c.vkEnumeratePhysicalDevices(instance, &pd_count, &phys);
    if (pd_count == 0) std.debug.panic("no Vulkan devices\n", .{});
    var props: c.VkPhysicalDeviceProperties = undefined;
    c.vkGetPhysicalDeviceProperties(phys, &props);
    std.debug.print("device: {s}\n", .{std.mem.sliceTo(&props.deviceName, 0)});

    // 3. Compute queue family
    var qf_count: u32 = 0;
    c.vkGetPhysicalDeviceQueueFamilyProperties(phys, &qf_count, null);
    var qfs: [16]c.VkQueueFamilyProperties = undefined;
    c.vkGetPhysicalDeviceQueueFamilyProperties(phys, &qf_count, &qfs);
    var qfi: u32 = 0;
    while (qfi < qf_count) : (qfi += 1) {
        if (qfs[qfi].queueFlags & c.VK_QUEUE_COMPUTE_BIT != 0) break;
    }

    // 4. Logical device + queue
    const prio: f32 = 1.0;
    var qci = std.mem.zeroes(c.VkDeviceQueueCreateInfo);
    qci.sType = c.VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qci.queueFamilyIndex = qfi;
    qci.queueCount = 1;
    qci.pQueuePriorities = &prio;
    var dci = std.mem.zeroes(c.VkDeviceCreateInfo);
    dci.sType = c.VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    dci.queueCreateInfoCount = 1;
    dci.pQueueCreateInfos = &qci;
    var device: c.VkDevice = undefined;
    check(c.vkCreateDevice(phys, &dci, null, &device), "vkCreateDevice");
    var queue: c.VkQueue = undefined;
    c.vkGetDeviceQueue(device, qfi, 0, &queue);

    // 5. Two host-visible storage buffers
    var memprops: c.VkPhysicalDeviceMemoryProperties = undefined;
    c.vkGetPhysicalDeviceMemoryProperties(phys, &memprops);
    const want = c.VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | c.VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
    const bytes: c.VkDeviceSize = n * @sizeOf(f32);

    const Buf = struct { buf: c.VkBuffer, mem: c.VkDeviceMemory };
    const makeBuffer = struct {
        fn go(dev: c.VkDevice, mp: c.VkPhysicalDeviceMemoryProperties, size: c.VkDeviceSize, flags: u32) Buf {
            var bci = std.mem.zeroes(c.VkBufferCreateInfo);
            bci.sType = c.VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
            bci.size = size;
            bci.usage = c.VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
            bci.sharingMode = c.VK_SHARING_MODE_EXCLUSIVE;

            var buf: c.VkBuffer = undefined;
            check(c.vkCreateBuffer(dev, &bci, null, &buf), "vkCreateBuffer");
            var req: c.VkMemoryRequirements = undefined;
            c.vkGetBufferMemoryRequirements(dev, buf, &req);
            var idx: u32 = 0;
            while (idx < mp.memoryTypeCount) : (idx += 1) {
                if (req.memoryTypeBits & (@as(u32, 1) << @intCast(idx)) != 0 and
                    mp.memoryTypes[idx].propertyFlags & flags == flags) break;
            }
            var mai = std.mem.zeroes(c.VkMemoryAllocateInfo);
            mai.sType = c.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
            mai.allocationSize = req.size;
            mai.memoryTypeIndex = idx;
            var mem: c.VkDeviceMemory = undefined;
            check(c.vkAllocateMemory(dev, &mai, null, &mem), "vkAllocateMemory");
            check(c.vkBindBufferMemory(dev, buf, mem, 0), "vkBindBufferMemory");
            return .{ .buf = buf, .mem = mem };
        }
    }.go;

    const in_buf = makeBuffer(device, memprops, bytes, want);
    const out_buf = makeBuffer(device, memprops, bytes, want);

    // Fill input: 0,1,2,...,n-1
    var mapped: ?*anyopaque = null;
    check(c.vkMapMemory(device, in_buf.mem, 0, bytes, 0, &mapped), "map in");
    const in_ptr: [*]f32 = @ptrCast(@alignCast(mapped));
    for (0..n) |i| in_ptr[i] = @floatFromInt(i);
    c.vkUnmapMemory(device, in_buf.mem);

    // 6. Descriptor set layout (2 storage buffers) + pipeline layout
    var bindings = [_]c.VkDescriptorSetLayoutBinding{
        .{ .binding = 0, .descriptorType = c.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, .descriptorCount = 1, .stageFlags = c.VK_SHADER_STAGE_COMPUTE_BIT, .pImmutableSamplers = null },
        .{ .binding = 1, .descriptorType = c.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, .descriptorCount = 1, .stageFlags = c.VK_SHADER_STAGE_COMPUTE_BIT, .pImmutableSamplers = null },
    };
    var dslci = std.mem.zeroes(c.VkDescriptorSetLayoutCreateInfo);
    dslci.sType = c.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    dslci.bindingCount = 2;
    dslci.pBindings = &bindings;
    var dsl: c.VkDescriptorSetLayout = undefined;
    check(c.vkCreateDescriptorSetLayout(device, &dslci, null, &dsl), "descSetLayout");

    // Declare the push-constant range so the layout matches the kernel's `pc` block.
    var pc_range = c.VkPushConstantRange{
        .stageFlags = c.VK_SHADER_STAGE_COMPUTE_BIT,
        .offset = 0,
        .size = @sizeOf(PushConstants),
    };
    var plci = std.mem.zeroes(c.VkPipelineLayoutCreateInfo);
    plci.sType = c.VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount = 1;
    plci.pSetLayouts = &dsl;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges = &pc_range;
    var pipeline_layout: c.VkPipelineLayout = undefined;
    check(c.vkCreatePipelineLayout(device, &plci, null, &pipeline_layout), "pipelineLayout");

    // 7. Shader module from the Zig-compiled SPIR-V
    const spv = @embedFile("vk_filter.spv");
    var smci = std.mem.zeroes(c.VkShaderModuleCreateInfo);
    smci.sType = c.VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = spv.len;
    smci.pCode = @ptrCast(@alignCast(spv.ptr));
    var module: c.VkShaderModule = undefined;
    check(c.vkCreateShaderModule(device, &smci, null, &module), "shaderModule");

    // 8. Compute pipeline (entry point "main")
    var stage = std.mem.zeroes(c.VkPipelineShaderStageCreateInfo);
    stage.sType = c.VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stage.stage = c.VK_SHADER_STAGE_COMPUTE_BIT;
    stage.module = module;
    stage.pName = "main";
    var cpci = std.mem.zeroes(c.VkComputePipelineCreateInfo);
    cpci.sType = c.VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage = stage;
    cpci.layout = pipeline_layout;
    var pipeline: c.VkPipeline = undefined;
    check(c.vkCreateComputePipelines(device, null, 1, &cpci, null, &pipeline), "computePipeline");

    // 9. Descriptor pool + set, point bindings at the buffers
    var pool_size = c.VkDescriptorPoolSize{ .type = c.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, .descriptorCount = 2 };
    var dpci = std.mem.zeroes(c.VkDescriptorPoolCreateInfo);
    dpci.sType = c.VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &pool_size;
    var pool: c.VkDescriptorPool = undefined;
    check(c.vkCreateDescriptorPool(device, &dpci, null, &pool), "descPool");

    var dsai = std.mem.zeroes(c.VkDescriptorSetAllocateInfo);
    dsai.sType = c.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = pool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsl;
    var dset: c.VkDescriptorSet = undefined;
    check(c.vkAllocateDescriptorSets(device, &dsai, &dset), "allocDescSet");

    var in_info = c.VkDescriptorBufferInfo{ .buffer = in_buf.buf, .offset = 0, .range = bytes };
    var out_info = c.VkDescriptorBufferInfo{ .buffer = out_buf.buf, .offset = 0, .range = bytes };
    var writes = [_]c.VkWriteDescriptorSet{
        blk: {
            var w = std.mem.zeroes(c.VkWriteDescriptorSet);
            w.sType = c.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
            w.dstSet = dset;
            w.dstBinding = 0;
            w.descriptorCount = 1;
            w.descriptorType = c.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            w.pBufferInfo = &in_info;
            break :blk w;
        },
        blk: {
            var w = std.mem.zeroes(c.VkWriteDescriptorSet);
            w.sType = c.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
            w.dstSet = dset;
            w.dstBinding = 1;
            w.descriptorCount = 1;
            w.descriptorType = c.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            w.pBufferInfo = &out_info;
            break :blk w;
        },
    };
    c.vkUpdateDescriptorSets(device, 2, &writes, 0, null);

    // 10. Command buffer: bind + dispatch N/64 workgroups
    var cpci2 = std.mem.zeroes(c.VkCommandPoolCreateInfo);
    cpci2.sType = c.VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    cpci2.queueFamilyIndex = qfi;
    var cmd_pool: c.VkCommandPool = undefined;
    check(c.vkCreateCommandPool(device, &cpci2, null, &cmd_pool), "cmdPool");

    var cbai = std.mem.zeroes(c.VkCommandBufferAllocateInfo);
    cbai.sType = c.VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = cmd_pool;
    cbai.level = c.VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    var cmd: c.VkCommandBuffer = undefined;
    check(c.vkAllocateCommandBuffers(device, &cbai, &cmd), "allocCmd");

    var bi = std.mem.zeroes(c.VkCommandBufferBeginInfo);
    bi.sType = c.VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = c.VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    check(c.vkBeginCommandBuffer(cmd, &bi), "beginCmd");
    c.vkCmdBindPipeline(cmd, c.VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    c.vkCmdBindDescriptorSets(cmd, c.VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_layout, 0, 1, &dset, 0, null);
    const push = PushConstants{ .threshold = threshold, .n = n };
    c.vkCmdPushConstants(cmd, pipeline_layout, c.VK_SHADER_STAGE_COMPUTE_BIT, 0, @sizeOf(PushConstants), &push);
    // ceil(n / wg_size) groups; the kernel's bounds check handles the remainder.
    c.vkCmdDispatch(cmd, (n + cfg.wg_size - 1) / cfg.wg_size, 1, 1);
    check(c.vkEndCommandBuffer(cmd), "endCmd");

    // 11. Submit + wait
    var si = std.mem.zeroes(c.VkSubmitInfo);
    si.sType = c.VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    check(c.vkQueueSubmit(queue, 1, &si, null), "queueSubmit");
    check(c.vkQueueWaitIdle(queue), "queueWaitIdle");

    // 12. Read back
    check(c.vkMapMemory(device, out_buf.mem, 0, bytes, 0, &mapped), "map out");
    const out_ptr: [*]f32 = @ptrCast(@alignCast(mapped));
    // Print a window of up to 16 elements at the tail (the kept, high values).
    const win: u32 = @min(n, 16);
    const start = n - win;
    std.debug.print("out[{d}..{d}] (input is 0..{d}):\n  ", .{ start, n, n - 1 });
    for (start..n) |i| std.debug.print("{d:>4} ", .{out_ptr[i]});
    std.debug.print("\n", .{});
    var kept: u32 = 0;
    var expected: u32 = 0;
    for (0..n) |i| {
        if (out_ptr[i] != 0) kept += 1;
        if (@as(f32, @floatFromInt(i)) > threshold) expected += 1;
    }
    std.debug.print("nonzero elements: {d} (expected {d})\n", .{ kept, expected });
    c.vkUnmapMemory(device, out_buf.mem);
}
