//! The same parallel-filter demo, written against the high-level `spock` API.
//! Compare with vk_host_vkzig.zig (~300 lines of raw Vulkan) — this is the point
//! of the abstraction layer.

const std = @import("std");
const spock = @import("spock");
const config = @import("config"); // generated by build.zig: wg_size

const filter_spv = @embedFile("filter.spv");
const dgemm_spv = @embedFile("dgemm.spv");

const Opts = struct {
    threshold: f32 = 128.0,
    n: u32 = 256,
    want_validation: bool = false,
    chain: bool = false,
};

fn parseArgs(args: std.process.Args) Opts {
    var opts = Opts{};

    var it = args.iterate();
    _ = it.skip(); // skip argv[0]
    while (it.next()) |arg| {
        if (std.mem.startsWith(u8, arg, "--threshold=")) {
            opts.threshold = std.fmt.parseFloat(f32, arg["--threshold=".len..]) catch opts.threshold;
        } else if (std.mem.startsWith(u8, arg, "--n=")) {
            opts.n = std.fmt.parseInt(u32, arg["--n=".len..], 10) catch opts.n;
        } else if (std.mem.eql(u8, arg, "--validate")) {
            opts.want_validation = true;
        } else if (std.mem.eql(u8, arg, "--chain")) {
            opts.chain = true;
        }
    }

    return opts;
}

pub fn main(init: std.process.Init) !void {

    // Runtime flags (same as the other hosts).
    var opts = parseArgs(init.minimal.args);
    if (opts.n == 0) opts.n = 1;

    try runSimpleKernel(init.gpa, opts);
    try runDgemm(init.gpa, opts);
}

fn runSimpleKernel(gpa: std.mem.Allocator, opts: Opts) !void {
    const PushConstants = extern struct { threshold: f32, n: u32 };

    // 1. Device setup — pick the largest GPU on the system.
    var ctx = try spock.Context.init(gpa, .{ .pick = .largest, .validate = opts.want_validation });
    defer ctx.deinit();
    std.debug.print("[spock] device: {s}\n", .{ctx.deviceName()});
    std.debug.print("config: n={d} wg_size={d} threshold={d}\n", .{ opts.n, config.wg_size, opts.threshold });

    // 2. Array creation — allocate, then fill the mapped host slice directly.
    var input = try spock.Buffer(f32).create(&ctx, opts.n);
    defer input.deinit();
    var output = try spock.Buffer(f32).create(&ctx, opts.n);
    defer output.deinit();

    for (input.slice(), 0..) |*v, i| v.* = @floatFromInt(i);
    output.fill(0);

    const groups = (opts.n + config.wg_size - 1) / config.wg_size;
    // Effective cutoff used to compute the "expected" count below.
    var eff_threshold = opts.threshold;

    if (!opts.chain) {
        // 3a. Single dispatch (async), then wait.
        var kernel = try spock.Kernel.create(&ctx, .{
            .spirv = filter_spv,
            .buffers = 2,
            .push_constant_size = @sizeOf(PushConstants),
        });
        defer kernel.deinit();

        const pc = PushConstants{ .threshold = opts.threshold, .n = opts.n };
        try kernel.dispatch(.{
            .buffers = &.{ input.raw(), output.raw() },
            .push_constant = std.mem.asBytes(&pc),
            .groups = .{ groups, 1, 1 },
        });
        try ctx.wait();
    } else {
        // 3b. Two filter passes chained in ONE submission through a scratch buffer:
        //     input --(t=threshold)--> tmp --(t=1.5*threshold)--> output
        // The Pipeline inserts a storage barrier between passes so pass 2 reads
        // pass 1's fully-written output. Both passes "keep > t", so the net cutoff
        // is the larger threshold. Two kernel instances because a kernel's single
        // descriptor set can't be rebound twice within one command buffer.
        var tmp = try spock.Buffer(f32).create(&ctx, opts.n);
        defer tmp.deinit();

        var pass1 = try spock.Kernel.create(&ctx, .{ .spirv = filter_spv, .buffers = 2, .push_constant_size = @sizeOf(PushConstants) });
        defer pass1.deinit();
        var pass2 = try spock.Kernel.create(&ctx, .{ .spirv = filter_spv, .buffers = 2, .push_constant_size = @sizeOf(PushConstants) });
        defer pass2.deinit();

        const t2 = opts.threshold * 1.5;
        eff_threshold = @max(opts.threshold, t2);
        const pc1 = PushConstants{ .threshold = opts.threshold, .n = opts.n };
        const pc2 = PushConstants{ .threshold = t2, .n = opts.n };

        var seq = try spock.Pipeline.create(&ctx);
        defer seq.deinit();
        try seq.addKernel(&pass1, .{ .buffers = &.{ input.raw(), tmp.raw() }, .push_constant = std.mem.asBytes(&pc1), .groups = .{ groups, 1, 1 } });
        try seq.addKernel(&pass2, .{ .buffers = &.{ tmp.raw(), output.raw() }, .push_constant = std.mem.asBytes(&pc2), .groups = .{ groups, 1, 1 } });
        try seq.submit();
        try ctx.wait();
        std.debug.print("chained 2 passes (t={d} then t={d})\n", .{ opts.threshold, t2 });
    }

    // 5. Copy results back to a plain host array.
    const host = try gpa.alloc(f32, opts.n);
    defer gpa.free(host);
    output.copyToHost(host);

    // Report.
    const win: u32 = @min(opts.n, 16);
    std.debug.print("out[{d}..{d}]:\n  ", .{ opts.n - win, opts.n });
    for (host[opts.n - win ..]) |v| std.debug.print("{d:>4} ", .{v});
    std.debug.print("\n", .{});
    var kept: u32 = 0;
    var expected: u32 = 0;
    for (host, 0..) |v, i| {
        if (v != 0) kept += 1;
        if (@as(f32, @floatFromInt(i)) > eff_threshold) expected += 1;
    }
    std.debug.print("nonzero elements: {d} (expected {d})\n", .{ kept, expected });
}

fn runDgemm(gpa: std.mem.Allocator, opts: Opts) !void {
    const PushConstants = @import("kernels/dgemm.zig").PushConstants;
    const WgSize = @import("kernels/dgemm.zig").WgSize;

    const print_mats: bool = false;

    const wg_size = WgSize.x; // Number of threads per block
    const M: u32 = 128;
    const N: u32 = 128;
    const K: u32 = 64;

    // 1. Device setup — pick the largest GPU on the system.
    var ctx = try spock.Context.init(gpa, .{ .pick = .largest, .validate = opts.want_validation });
    defer ctx.deinit();
    std.debug.print("[spock] device: {s}\n", .{ctx.deviceName()});

    // 2. Array creation — allocate, then fill the mapped host slice directly.
    var Amat = try spock.Buffer(f64).create(&ctx, M * K);
    defer Amat.deinit();
    var Bmat = try spock.Buffer(f64).create(&ctx, K * N);
    defer Bmat.deinit();
    var Cmat = try spock.Buffer(f64).create(&ctx, M * N);
    defer Cmat.deinit();

    for (Amat.slice(), 0..) |*v, i| v.* = @floatFromInt(i);
    for (Bmat.slice(), 0..) |*v, i| v.* = @floatFromInt(i);
    Cmat.fill(0);

    if (print_mats) {
        std.debug.print("A:\n", .{});
        for (0..M) |i| {
            for (0..K) |j| {
                std.debug.print("{d:>4} ", .{Amat.slice()[j + i * K]});
            }
            std.debug.print("\n", .{});
        }
        std.debug.print("\n", .{});

        std.debug.print("B:\n", .{});
        for (0..K) |i| {
            for (0..N) |j| {
                std.debug.print("{d:>4} ", .{Bmat.slice()[j + i * N]});
            }
            std.debug.print("\n", .{});
        }
        std.debug.print("\n", .{});
    }

    const groups = @divCeil(M * N, wg_size);

    // 3a. Single dispatch (async), then wait.
    var kernel = try spock.Kernel.create(&ctx, .{
        .spirv = dgemm_spv,
        .buffers = 3,
        .push_constant_size = @sizeOf(PushConstants),
        .entry = "dgemm",
    });
    defer kernel.deinit();

    const pc = PushConstants{
        .M = M,
        .N = N,
        .K = K,
        .alpha = 1.0,
        .beta = 0.0,
    };

    try kernel.dispatch(.{
        .buffers = &.{ Amat.raw(), Bmat.raw(), Cmat.raw() },
        .push_constant = std.mem.asBytes(&pc),
        .groups = .{ groups, 1, 1 },
    });
    try ctx.wait();

    // 5. Copy results back to a plain host array.
    const host = try gpa.alloc(f64, M * N);
    defer gpa.free(host);
    Cmat.copyToHost(host);

    // Report.

    if (print_mats) {
        std.debug.print("C:\n", .{});
        for (0..M) |i| {
            for (0..N) |j| {
                std.debug.print("{d:>4} ", .{host[j + i * N]});
            }
            std.debug.print("\n", .{});
        }
        std.debug.print("\n", .{});
    } else {
        const win: u32 = @min(M * N, 16);
        std.debug.print("out[{d}..{d}]:\n  ", .{ M * N - win, M * N });
        for (host[M * N - win ..]) |v| std.debug.print("{d:>4} ", .{v});
        std.debug.print("\n", .{});
    }
}
